USE TrabFinalSI2

/* ************************************* */
IF(EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Admin'))
	DROP TABLE dbo.Admin
IF(EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Afecto'))
	DROP TABLE Afecto
IF(EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Habilitado'))
	DROP TABLE Habilitado
IF(EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Relatorio'))
	DROP TABLE Relatorio
/* ************************************* */
IF(EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Trabalho'))
	DROP TABLE Trabalho
IF(EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Ocorrencia'))
	DROP TABLE Ocorrencia
IF(EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='AreaIntervencao'))
	DROP TABLE AreaIntervencao
/* ************************************* */
IF(EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Coordenador'))
	DROP TABLE Coordenador
IF(EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Sector'))
	DROP TABLE Sector
IF(EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='estadoOcorr'))
	DROP TABLE estadoOcorr
IF(EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='tipo'))
	DROP TABLE tipo
/* ************************************* */
IF(EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Funcionario'))
	DROP TABLE Funcionario
IF(EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Instalacao'))
	DROP TABLE Instalacao
/* ************************************* */
IF(EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='estadoFunc'))
	DROP TABLE estadoFunc
IF(EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Empresa'))
	DROP TABLE Empresa




	





